services:
  app:
    build: .
    container_name: bun-app
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - '8000'

    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  mongodb-data:
  redis-data:
