import { Router } from 'express';
const router = Router();

import authRoutes from './auth.routes.js';
router.use('/auth', authRoutes);
import categoryRoutes from './category.routes.js';
router.use('/category', categoryRoutes);
import productRoutes from './product.routes.js';
router.use('/product', productRoutes);
import customerRoutes from './customer.routes.js';
router.use('/customer', customerRoutes);
import invoiceRoutes from './invoice.routes.js';
router.use('/invoice', invoiceRoutes);
import adsRoutes from './ads.routes.js';
router.use('/ads', adsRoutes);
import planRoutes from './plan.routes.js';
router.use('/plan', planRoutes);
import subscriptionRoutes from './subscription.routes.js';
router.use('/subscription', subscriptionRoutes);
import storeRoutes from './store.routes.js';
router.use('/store', storeRoutes);
import hsnCodeRoutes from './hsnCode.routes.js';
router.use('/hsncode', hsnCodeRoutes);
import feedbackRoutes from './feedback.routes.js';
router.use('/feedback', feedbackRoutes);
import faqRoutes from './faq.routes.js';
router.use('/faq', faqRoutes);
import appVersionRoutes from './appVersion.routes.js';
router.use('/app-version', appVersionRoutes);
import expenseHeadRoutes from './expenseHead.routes.js';
router.use('/expense-head', expenseHeadRoutes);
import expenseRoutes from './expense.routes.js';
router.use('/expense', expenseRoutes);
import howToVideoRoutes from './howToVideo.routes.js';
router.use('/how-to-videos', howToVideoRoutes);
import vendorRoutes from './vendor.routes.js';
router.use('/vendor', vendorRoutes);
import purchaseRoutes from './purchase.routes.js';
router.use('/purchase', purchaseRoutes);
import roleRoutes from './role.routes.js';
router.use('/role', roleRoutes);
import helplineRoutes from './helpline.routes.js';
router.use('/helpline', helplineRoutes);
import heroRoutes from './hero.routes.js';
router.use('/hero', heroRoutes);
import aboutRoutes from './about.routes.js';
router.use('/about', aboutRoutes);
import testimonialRoutes from './testimonial.route.js';
router.use('/testimonial', testimonialRoutes);

export default router;
