export const StockTransactionType = {
  ADJUSTMENT: 'ADJUSTMENT',
  PURCHASE: 'PURCHASE',
  SALE: 'SALE',
  PURCHASE_RETURN: 'PURCHASE_RETURN',
  SALE_RETURN: 'SALE_RETURN',
  TRANSFER: 'TRANSFER',
  PURCHASE_REVERSE: 'PURCHASE_REVERSE',
  STOCK_REDUCE: 'STOCK_REDUCE',
  RETURN_TO_VENDOR: 'RETURN_TO_VENDOR',
  DAMAGE: 'DAMAGE',
};