export const StockTransactionType = {
  ADJUSTMENT: 'ADJUSTMENT',
  PURCHASE: 'PURCHASE',
  SALE: 'SALE',
  PURCHASE_RETURN: 'PURCHASE_RETURN',
  SALE_RETURN: 'SALE_RETURN',
  TRANSFER: 'TRANSFER',
  PURCHASE_REVERSE: 'PURCHASE_REVERSE',
};
