server {
    listen 80;
    server_name amdaani.v1.amptechnology.in;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name amdaani.v1.amptechnology.in;

    ssl_certificate /etc/letsencrypt/live/amdaani.v1.amptechnology.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/amdaani.v1.amptechnology.in/privkey.pem;

    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;

    location / {
        proxy_pass http://app:8010;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 90;
    }
}