
server {
    listen 80;
    server_name amdaani.v1.amptechnology.in;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

