name: AmdaaniBackend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Deploy Via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/temp_amdaani_backend
            git pull origin main
            echo "${{ secrets.ENV_FILE }}" > .env

            if [ ! -f "./certbot/conf/live/amdaani.v1.amptechnology.in/fullchain.pem" ]; then
              echo "No certs found — running first-time SSL init..."
              bash ./init-ssl.sh
            else
              echo "Certs exist — redeploying..."
              docker compose up -d --build --remove-orphans
              docker compose exec nginx nginx -s reload
            fi

            docker image prune -f