name: AmdaaniBackend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Deploy Via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          command_timeout: 20m
          script: |
            # Clone repo if first time
            if [ ! -d "/home/ubuntu/temp_amdaani_backend" ]; then
              git clone https://github.com/amptechnology-dev/temp_amdaani_backend.git /home/ubuntu/temp_amdaani_backend
            fi

            cd /home/ubuntu/temp_amdaani_backend

            # Pull latest code
            git fetch origin main
            git reset --hard origin/main
            git pull origin main

            # Write env file
            echo "${{ secrets.ENV_FILE }}" > .env

            # Fix certbot permissions
            mkdir -p ./certbot/www/.well-known/acme-challenge ./certbot/conf
            sudo chown -R ubuntu:ubuntu ./certbot
            chmod -R 755 ./certbot

            # Run SSL setup (skips cert if already exists)
            bash ./init-ssl.sh

            # Cleanup old images
            docker image prune -f

            echo "Deploy complete!"